name: On PR Merge - Build & Push

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build & Push All
        run: ./build.bash push
